services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dimuthu
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
  eureka-server:
    image: dimuthuwa/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal
    depends_on:
      - zipkin
  apigw:
    image: dimuthuwa/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal
    depends_on:
      - zipkin
      - eureka-server
  customer:
    image: dimuthuwa/customer:latest
    container_name: customer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server
  fraud:
    image: dimuthuwa/fraud:latest
    container_name: fraud
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server
  notification:
    image: dimuthuwa/notification:latest
    container_name: notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - eureka-server

networks:
  postgres:
    driver: bridge
  internal:
    driver: bridge

volumes:
  postgres:
  pgadmin: