server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'dimuthu'
    url: jdbc:postgresql://localhost:5432/customer
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true